# Running SERVICES
# - traefik for the proxy for the wordpress
# - database mysql to work with wordpress
# - wordpress
#-----------------------------------------------
# To use this file:
# $ ln -s services.yml docer-compose.yml
# $ docker-compose up -d
#

version: "3"

#===============================================
networks:
  www:
    external: true
  internal:
    external: false
#===============================================
services:
  proxy:
    image: traefik:1.7.2-alpine
    networks:
      - www
    labels:
      - traefik.frontend.rule=Host:monitor.{{ ansible_domain }}
      - traefik.port=8080
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json

#-----------------------------------------------
  dbms:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
    networks:
      - internal
    labels:
      - traefik.enable=false
    depends_on:
      - proxy

#-----------------------------------------------
# ixorg is the name of project
  ixorg:
    image: wordpress:4.9.8-apache
    networks:
      - internal
      - www
    labels:
      - traefik.backend=ixorg
      - traefik.frontend.rule=Host:blog.{{ ansible_domain }}
      - traefik.docker.network=www
      - traefik.port=80
    depends_on:
      - proxy
      - dbms

#-----------------------------------------------
  dba:
    image: adminer:4.6.3-standalone
    networks:
      - internal
      - www
    labels:
      - traefik.backend=dba
      - traefik.frontend.rule=Host:dba.{{ ansible_domain }}
      - traefik.docker.network=www
      - traefik.port=8080
    depends_on:
      - proxy
      - dbms

#-----------------------------------------------
# End of services.yml
