# What playbook simply install apache2-utils to get htpasswd
# htpasswd is a util to generate admin password fot Traefik

- hosts:  vm-germany-02

  become: true

  tasks:
    - name: Install htpasswd as part of apache2-utils
      apt:
        name:
           - apache2-utils
        state: present
        update_cache: yes

# ----------------------------------
# End of playbook htpasswd.yml
