# What playbook does:
# Simply install apache2-utils to get htpasswd.
# htpasswd will use to generate admin password for Traefik
#
# Additional will install packets to use with the
# Docker-compose module Ansible.
#
# And will use Python3 as the default Python interpreter
#

- hosts:  vm-germany-02

  vars:
    ansible_python_interpreter: /usr/bin/python3

  become: true

  tasks:
    - name: Install htpasswd as part of apache2-utils
      apt:
        name:
           - apache2-utils
        state: present
        update_cache: yes

# Install pip to use to install docker and docker-compose
# python libraries for the docker-compose module Ansible

    - name: Install pip3
      apt:
        name:
           - python3-pip
        state: present
        update_cache: yes

    - name: Install pip
      apt:
        name:
           - python-pip
        state: present
        update_cache: yes

# Install Python libraries to use with the docker-compose
# module

    - name: Install Python Libraries docker and docker-compose.
      pip:
        name:
           - docker
           - docker-compose
        executable: pip3

# ----------------------------------
# End of playbook htpasswd.yml
