# What playbook does:
# 1. Check that htpasswd is installed
# 2. Generate a password: htpasswd -nb user_name user_password
# 3. To print admin password use: ansible-playbook -vv
# 4. Generate, keep and put into it's place config file
#    for the Traefic (traefic.toml)
#    Traefik will use with the support Let's Encrypt
# ----------------
# Descriptions:
# Before use this playbook need to write your e-mail address
# and your domain.
# ----------------
# Warning:
# This playbook each times to launch it
# will generate a new password for the admin user
# and recreate traefik.toml with the new admin password
# ----------------
# Tasks for the future:
# Сделать так, чтобы если пароль администратора
# уже был сгенерирован и, соответственно, создан
# конфигурационный файл для Traefik, то пароль для
# администратора больше не генерировать и не перезаписывать
# конфигурационный файл.


- hosts:  vm-germany-02

  vars:
    ansible_python_interpreter: /usr/bin/python3

    asible_admin_htpasswd:   123qwe
    ansible_email:           your_email@your_provider.provider_zone
    ansible_domain:          your_domain.your_zone

  tasks:

    - name: Check htpasswd
      command: which htpasswd
      register: ansible_htpasswd_path

    - name: Print PATH of htpasswd
      debug: 
         msg: "{{ ansible_htpasswd_path.stdout }}"

    - name: Generate password
      command:  htpasswd -nb admin {{ asible_admin_htpasswd }}
      register: ansible_admin_password

    - name: Print admin password. To see it enter option -vv
      debug:
         msg: "{{ ansible_admin_password.stdout }}"
#         verbosity: 2

    - name: Get Local PATH 
      shell:
            cmd: "pwd"
      register: ansible_user_home_path

    - name: Create working directory for Docker
      file:
         path:   "{{ ansible_user_home_path.stdout_lines[0] }}/Docker"
         state:  directory
      register: ansible_working_dir

    - name: Print working directory
      debug:
         msg: "{{ ansible_working_dir }}"

    - name: Generate traefik.toml config file
      template:
         src:  traefik.toml
         dest: "{{ansible_working_dir.path }}/traefik.toml"

    - name: Create acme.json file to support Let's Encrypt
      file:
         path: "{{ansible_working_dir.path }}/acme.json"
         state: touch
         mode:  0600

    - name: Generate docker-compose.yml file
      template:
         src:  ../Docker/services.yml
         dest: "{{ansible_working_dir.path }}/docker-compose.yml"

    - name: Launch services as a Docker
      docker_compose:
         project_src: "{{ ansible_working_dir.path }}"
      register: output

    - name: Print status of running docker
      debug:
         msg: "{{ output }}"

# ----------------------------------
# End of playbook traefik.yml
