defaultEntryPoints = ["http", "https"]

[entryPoints]
   [entryPoints.dashboard]
      address = ":8080"
      [entryPoints.dashboard.auth.basic]
         users = ["{{ admin_password.stdout }}"]
   [entryPoints.http]
      address = ":80"
         [entryPoints.http.redirect]
         entryPoints = "https"
   [entryPoints.https]
      address = ":443"
         [entryPoints.https.tls]

[api]
entrypoint = "dashboard"

[acme]
email = "email"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
domain = "domain"
watch = true
network = "www"
